=== OphirOren/genai-attacks/validation/schemas/tactic.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "frameworks": {
      "items": {
        "properties": {
          "href": {
            "format": "uri",
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        },
        "required": [
          "title",
          "id",
          "href"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "id": {
      "type": "string"
    },
    "summary": {
      "type": "string"
    },
    "tactic_order": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    }
  },
  "required": [
    "tactic_order",
    "title",
    "summary",
    "frameworks",
    "id"
  ],
  "type": "object"
}

=== OphirOren/genai-attacks/tactics/defense_evasion.json
{
  "description": "",
  "frameworks": [
    {
      "href": "https://atlas.mitre.org/tactics/AML.TA0007",
      "id": "AML.TA0007",
      "title": "MITRE ATLAS"
    },
    {
      "href": "https://attack.mitre.org/tactics/TA0005/",
      "id": "TA0005",
      "title": "MITRE ATT&CK"
    }
  ],
  "id": "tactics/defense_evasion",
  "summary": "The adversary is trying to avoid being detected by security software and native controls.",
  "tactic_order": 7,
  "title": "Defense Evasion"
}

=== OphirOren/genai-attacks/tactics/impact.json
{
  "description": "",
  "frameworks": [
    {
      "href": "https://atlas.mitre.org/tactics/AML.TA0011",
      "id": "AML.TA0011",
      "title": "MITRE ATLAS"
    },
    {
      "href": "https://attack.mitre.org/tactics/TA0040/",
      "id": "TA0040",
      "title": "MITRE ATT&CK"
    }
  ],
  "id": "tactics/impact",
  "summary": "The adversary is trying to communicate with compromised systems to control them.",
  "tactic_order": 14,
  "title": "Impact"
}
