=== OphirOren/genai-attacks/validation/schemas/tactics.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "frameworks": {
      "items": {
        "properties": {
          "framework_id": {
            "type": "string"
          },
          "framework_title": {
            "type": "string"
          },
          "href": {
            "format": "uri",
            "type": "string"
          }
        },
        "required": [
          "framework_title",
          "framework_id",
          "href"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "id": {
      "$ref": "common.schema.json#/definitions/id"
    },
    "summary": {
      "type": "string"
    },
    "tactic_order": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    }
  },
  "required": [
    "tactic_order",
    "title",
    "summary",
    "frameworks",
    "id"
  ],
  "type": "object"
}

=== OphirOren/genai-attacks/tactics/resource_development.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "AML.TA0005",
      "framework_title": "MITRE ATLAS",
      "href": "https://atlas.mitre.org/tactics/AML.TA0003"
    },
    {
      "framework_id": "TA0042",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0042/"
    }
  ],
  "id": "$gai-tactics/resource_development",
  "summary": "The adversary is trying to establish resources they can use to support operations.",
  "tactic_order": 2,
  "title": "Resource Development"
}

=== OphirOren/genai-attacks/tactics/persistence.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "AML.TA0006",
      "framework_title": "MITRE ATLAS",
      "href": "https://atlas.mitre.org/tactics/AML.TA0006"
    },
    {
      "framework_id": "TA0003",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0003/"
    }
  ],
  "id": "$gai-tactics/persistence",
  "summary": "Keep your malicious prompt there for future conversations",
  "tactic_order": 5,
  "title": "Persistence"
}

=== OphirOren/genai-attacks/tactics/reconnaissance.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "AML.TA0002",
      "framework_title": "MITRE ATLAS",
      "href": "https://atlas.mitre.org/tactics/AML.TA0002/"
    },
    {
      "framework_id": "TA0043",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0043/"
    }
  ],
  "id": "$gai-tactics/reconnaissance",
  "summary": "The adversary is trying to gather information about the GenAI system they can use to plan future operations.",
  "tactic_order": 1,
  "title": "Reconnaissance"
}

=== OphirOren/genai-attacks/tactics/initial_access.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "AML.TA0004",
      "framework_title": "MITRE ATLAS",
      "href": "https://atlas.mitre.org/tactics/AML.TA0004"
    },
    {
      "framework_id": "TA0001",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0001/"
    }
  ],
  "id": "$gai-tactics/initial_access",
  "summary": "Get your text into the LLM prompt",
  "tactic_order": 3,
  "title": "Initial Access"
}

=== OphirOren/genai-attacks/tactics/exfiltration.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "AML.TA0009",
      "framework_title": "MITRE ATLAS",
      "href": "https://atlas.mitre.org/tactics/AML.TA0009"
    },
    {
      "framework_id": "TA0009",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0009/"
    }
  ],
  "id": "$gai-tactics/exfiltration",
  "summary": "The adversary is trying to steal data or other information from your genai system.",
  "tactic_order": 13,
  "title": "Exfiltration"
}

=== OphirOren/genai-attacks/tactics/discovery.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "AML.TA0008",
      "framework_title": "MITRE ATLAS",
      "href": "https://atlas.mitre.org/tactics/AML.TA0008"
    },
    {
      "framework_id": "TA0007",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0007/"
    }
  ],
  "id": "$gai-tactics/discovery",
  "summary": "Understand the capabilities and mitigations in place.",
  "tactic_order": 9,
  "title": "Discovery"
}

=== OphirOren/genai-attacks/tactics/credential_access.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "AML.TA0013",
      "framework_title": "MITRE ATLAS",
      "href": "https://atlas.mitre.org/tactics/AML.TA0013"
    },
    {
      "framework_id": "TA0006",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0006/"
    }
  ],
  "id": "$gai-tactics/credential_access",
  "summary": "The adversary is trying to steal account names and passwords.",
  "tactic_order": 8,
  "title": "Credential Access"
}

=== OphirOren/genai-attacks/tactics/collection.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "AML.TA0009",
      "framework_title": "MITRE ATLAS",
      "href": "https://atlas.mitre.org/tactics/AML.TA0009"
    },
    {
      "framework_id": "TA0009",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0009/"
    }
  ],
  "id": "$gai-tactics/collection",
  "summary": "The adversary is trying to gather data, artifacts and other related information relevant to their goal.",
  "tactic_order": 11,
  "title": "Collection"
}
