=== OphirOren/genai-attacks/validation/schemas/tactics.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "frameworks": {
      "items": {
        "properties": {
          "framework_id": {
            "type": "string"
          },
          "framework_title": {
            "type": "string"
          },
          "href": {
            "format": "uri",
            "type": "string"
          }
        },
        "required": [
          "framework_title",
          "framework_id",
          "href"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "id": {
      "$ref": "common.schema.json#/definitions/id"
    },
    "summary": {
      "type": "string"
    },
    "tactic_order": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    }
  },
  "required": [
    "tactic_order",
    "title",
    "summary",
    "frameworks",
    "id"
  ],
  "type": "object"
}

=== OphirOren/genai-attacks/tactics/command_and_control.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "TA0011",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0011/"
    }
  ],
  "id": "$gai-tactics/command_and_control",
  "summary": "The adversary is trying to communicate with compromised systems to control them.",
  "tactic_order": 12,
  "title": "Command and Control"
}

=== OphirOren/genai-attacks/tactics/privilege_escalation.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "AML.TA0012",
      "framework_title": "MITRE ATLAS",
      "href": "https://atlas.mitre.org/tactics/AML.TA0012"
    },
    {
      "framework_id": "TA0004",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0004/"
    }
  ],
  "id": "$gai-tactics/privilege_escalation",
  "summary": "Confused deputy / Request forgery",
  "tactic_order": 6,
  "title": "Privilege Escalation"
}

=== OphirOren/genai-attacks/tactics/lateral_movement.json
{
  "description": "",
  "frameworks": [
    {
      "framework_id": "TA0008",
      "framework_title": "MITRE ATT&CK",
      "href": "https://attack.mitre.org/tactics/TA0008/"
    }
  ],
  "id": "$gai-tactics/lateral_movement",
  "summary": "The adversary is trying to move through your environment.",
  "tactic_order": 10,
  "title": "Lateral Movement"
}
