=== OphirOren/genai-attacks/validation/schemas/techniques.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "frameworks": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "id": {
      "$ref": "common.schema.json#/definitions/id"
    },
    "references": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "href": {
            "format": "uri",
            "type": "string"
          },
          "ref_author": {
            "allOf": [
              {
                "$ref": "common.schema.json#/definitions/id"
              },
              {
                "pattern": "authors/"
              }
            ]
          },
          "ref_title": {
            "type": "string"
          }
        },
        "required": [
          "href",
          "ref_title"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "summary": {
      "type": "string"
    },
    "tactics": {
      "items": {
        "allOf": [
          {
            "$ref": "common.schema.json#/definitions/id"
          },
          {
            "pattern": "tactics/"
          }
        ]
      },
      "type": "array"
    },
    "title": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "references",
    "summary",
    "tactics",
    "title"
  ],
  "type": "object"
}

=== OphirOren/genai-attacks/procedures/ascii_smuggling.json
{
  "description": "",
  "frameworks": [],
  "id": "$gai-techniques/ascii_smuggling",
  "references": [
    {
      "href": "https://embracethered.com/blog/posts/2024/hiding-and-finding-text-with-unicode-tags/",
      "ref_author": "$gai-authors/johann_rehberger.json",
      "ref_title": "Microsoft Copilot: From Prompt Injection to Exfiltration of Personal Information."
    }
  ],
  "summary": "A vulnerability in Microsoft 365 Copilot that allowed the theft of a users emails and other personal information. ",
  "tactics": [
    "tactics/defense_evasion.json"
  ],
  "title": "Microsoft Copilot: From Prompt Injection to Exfiltration of Personal Information"
}

=== OphirOren/genai-attacks/techniques/ascii_smuggling.json
{
  "description": "",
  "frameworks": [],
  "id": "$gai-techniques/ascii_smuggling",
  "references": [
    {
      "href": "https://twitter.com/goodside/status/1745511940351287394",
      "ref_author": "$gai-authors/riley_goodside.json",
      "ref_title": "Tweeter thread on the discovery of ASCII Smuggling."
    },
    {
      "href": "https://embracethered.com/blog/posts/2024/hiding-and-finding-text-with-unicode-tags/",
      "ref_author": "$gai-authors/johann_rehberger.json",
      "ref_title": "ASCII Smuggler Tool: Crafting Invisible Text and Decoding Hidden Codes."
    },
    {
      "href": "https://en.wikipedia.org/wiki/Tags_(Unicode_block)",
      "ref_title": "Tags (Unicode block)"
    }
  ],
  "summary": "The adversary uses Tags Unicode Block to write instructions that are visible to machine but not to humans.",
  "tactics": [
    "$gai-tactics/defense_evasion.json"
  ],
  "title": "ASCII SMuggling"
}
