=== OphirOren/genai-attacks/schema/prodecures.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "tactic_order": {
            "type": "integer"
        },
        "title": {
            "type": "string"
        },
        "summary": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "frameworks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "href": {
                        "type": "string",
                        "format": "uri"
                    }
                },
                "required": ["title", "id", "href"]
            }
        }
    },
    "required": ["tactic_order", "title", "summary", "frameworks"]
}

=== OphirOren/genai-attacks/procedures/credential_access.json
{
    "tactic_order": 8,
    "title": "Credential Access",
    "summary": "The adversary is trying to steal account names and passwords.",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATLAS", "id": "AML.TA0013", "href": "https://atlas.mitre.org/tactics/AML.TA0013"},
        {"title": "MITRE ATT&CK", "id": "TA0006", "href": "https://attack.mitre.org/tactics/TA0006/"}
    ]
}

=== OphirOren/genai-attacks/procedures/command_and_control.json
{
    "tactic_order": 11,
    "title": "Command and Control",
    "summary": "The adversary is trying to communicate with compromised systems to control them.",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATT&CK", "id": "TA0011", "href": "https://attack.mitre.org/tactics/TA0011/"}
    ]
}

=== OphirOren/genai-attacks/procedures/privilege_escalation.json
{
    "tactic_order": 6,
    "title": "Privilege Escalation",
    "summary": "Confused deputy / Request forgery",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATLAS", "id": "AML.TA0012", "href": "https://atlas.mitre.org/tactics/AML.TA0012"},
        {"title": "MITRE ATT&CK", "id": "TA0004", "href": "https://attack.mitre.org/tactics/TA0004/"}
    ]
}

=== OphirOren/genai-attacks/procedures/initial_access.json
{
    "tactic_order": 3,
    "title": "Initial Access",
    "summary": "Get your text into the LLM prompt",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATLAS", "id": "AML.TA0004", "href": "https://atlas.mitre.org/tactics/AML.TA0004"},
        {"title": "MITRE ATT&CK", "id": "TA0001", "href": "https://attack.mitre.org/tactics/TA0001/"}
    ]
}

=== OphirOren/genai-attacks/procedures/execution.json
{
    "tactic_order": 4,
    "title": "Execution",
    "summary": "Make the LLM interpret your text as instructions not data",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATLAS", "id": "AML.TA0005", "href": "https://atlas.mitre.org/tactics/AML.TA0005"},
        {"title": "MITRE ATT&CK", "id": "TA0002", "href": "https://attack.mitre.org/tactics/TA0002/"}
    ]
}
