=== OphirOren/genai-attacks/schema/prodecures.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "tactic_order": {
            "type": "integer"
        },
        "title": {
            "type": "string"
        },
        "summary": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "frameworks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "href": {
                        "type": "string",
                        "format": "uri"
                    }
                },
                "required": ["title", "id", "href"]
            }
        }
    },
    "required": ["tactic_order", "title", "summary", "frameworks"]
}

=== OphirOren/genai-attacks/procedures/exfiltration.json
{
    "tactic_order": 12,
    "title": "Exfiltration",
    "summary": "The adversary is trying to steal data or other information from your genai system.",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATLAS", "id": "AML.TA0009", "href": "https://atlas.mitre.org/tactics/AML.TA0009"},
        {"title": "MITRE ATT&CK", "id": "TA0009", "href": "https://attack.mitre.org/tactics/TA0009/"}
    ]
}

=== OphirOren/genai-attacks/procedures/collection.json
{
    "tactic_order": 10,
    "title": "Collection",
    "summary": "The adversary is trying to gather data, artifacts and other related information relevant to their goal.",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATLAS", "id": "AML.TA0009", "href": "https://atlas.mitre.org/tactics/AML.TA0009"},
        {"title": "MITRE ATT&CK", "id": "TA0009", "href": "https://attack.mitre.org/tactics/TA0009/"}
    ]
}

=== OphirOren/genai-attacks/procedures/persistence.json
{
  "description": "",
  "frameworks": [
    {
      "href": "https://atlas.mitre.org/tactics/AML.TA0006",
      "id": "AML.TA0006",
      "title": "MITRE ATLAS"
    },
    {
      "href": "https://attack.mitre.org/tactics/TA0003/",
      "id": "TA0003",
      "title": "MITRE ATT&CK"
    }
  ],
  "summary": "Keep your malicious prompt there for future conversations",
  "tactic_order": 5,
  "title": "Persistence"
}

=== OphirOren/genai-attacks/procedures/defense_evasion.json
{
    "tactic_order": 7,
    "title": "Defense Evasion",
    "summary": "The adversary is trying to avoid being detected by security software and native controls.",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATLAS", "id": "AML.TA0007", "href": "https://atlas.mitre.org/tactics/AML.TA0007"},
        {"title": "MITRE ATT&CK", "id": "TA0005", "href": "https://attack.mitre.org/tactics/TA0005/"}
    ]
}

=== OphirOren/genai-attacks/procedures/discovery.json
{
    "tactic_order": 9,
    "title": "Discovery",
    "summary": "Understand the capabilities and mitigations in place.",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATLAS", "id": "AML.TA0008", "href": "https://atlas.mitre.org/tactics/AML.TA0008"},
        {"title": "MITRE ATT&CK", "id": "TA0007", "href": "https://attack.mitre.org/tactics/TA0007/"}
    ]
}

=== OphirOren/genai-attacks/procedures/reconnaissance.json
{
    "tactic_order": 1,
    "title": "Reconnaissance",
    "summary": "The adversary is trying to gather information about the GenAI system they can use to plan future operations.",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATLAS", "id": "AML.TA0002", "href": "https://atlas.mitre.org/tactics/AML.TA0002/"},
        {"title": "MITRE ATT&CK", "id": "TA0043", "href": "https://attack.mitre.org/tactics/TA0043/"}
    ]
}

=== OphirOren/genai-attacks/procedures/resource_development.json
{
  "description": "",
  "frameworks": [
    {
      "href": "https://atlas.mitre.org/tactics/AML.TA0003",
      "id": "AML.TA0005",
      "title": "MITRE ATLAS"
    },
    {
      "href": "https://attack.mitre.org/tactics/TA0042/",
      "id": "TA0042",
      "title": "MITRE ATT&CK"
    }
  ],
  "summary": "The adversary is trying to establish resources they can use to support operations.",
  "tactic_order": 2,
  "title": "Resource Development"
}

=== OphirOren/genai-attacks/procedures/impact.json
{
    "tactic_order": 12,
    "title": "Impact",
    "summary": "The adversary is trying to communicate with compromised systems to control them.",
    "description": "",
    "frameworks": [
        {"title": "MITRE ATLAS", "id": "AML.TA0011", "href": "https://atlas.mitre.org/tactics/AML.TA0011"},
        {"title": "MITRE ATT&CK", "id": "TA0040", "href": "https://attack.mitre.org/tactics/TA0040/"}
    ]
}
